name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
              run: bun install

            - name: Build Project
              run: export NODE_OPTIONS="--max-old-space-size=8192" && bun run build
              env:
                  CI: False

            - name: Install azcopy
              uses: kheiakiyama/install-azcopy-action@v1
              with:
                  version: 'v10'

            - name: Deploy to AkrualWebsite
              run: |
                  azcopy_v10 remove '${{ secrets.AKRUAL_WEB_AZURE_STORAGE_SAS }}' --recursive
                  azcopy_v10 copy './.vercel/output/static/*' '${{ secrets.AKRUAL_WEB_AZURE_STORAGE_SAS }}' --recursive

            - name: Purge cache
              uses: nathanvaughn/actions-cloudflare-purge@master
              if: success()
              with:
                  cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
                  cf_auth: ${{ secrets.CLOUDFLARE_AUTH_TOKEN }}
